[package]
name = "sora-on-rust"
edition = "2024"
version = "1.7.4"

[dependencies]
anyhow = "1.0.102"
async-trait = "0.1.89"
chrono = "0.4.44"
colored = "3.1.1"
dhat = { version = "0.3.3", optional = true }
dotenvy = "0.15.7"
env_logger = "0.11"
libc = "0.2.186"
linkme = "0.3.36"
log = "0.4"
mimalloc = { version = "0.1.48", optional = true }
qr2term = "0.3.3"
tikv-jemallocator = { version = "0.7", optional = true }
toml = "1.1.2"

[features]
default = ["stable"]

stable = ["dep:tikv-jemallocator"]
performance = ["dep:mimalloc"]
profiling = ["dep:dhat"]

[dependencies.dashmap]
version = "6.1.0"
features = ["serde"]

[dependencies.rand]
version = "0.10.1"
features = ["std"]

[dependencies.http]
version = "1.5"

[dependencies.reqwest]
version = "0.13.2"
default-features = false
features = ["json", "query", "rustls-no-provider", "http2", "charset"]

[dependencies.rustls]
version = "0.23"
default-features = false
features = ["ring", "std", "tls12"]

[dependencies.serde]
version = "1.0.228"
features = ["derive"]

[dependencies.serde_json]
version = "1.0"

[dependencies.tokio]
version = "1.53"
features = ["macros", "rt-multi-thread", "fs", "process", "signal"]

[dependencies.whatsapp-rust]
version = "0.7"
features = ["signal", "sqlite-storage", "tokio-native", "tokio-runtime", "tokio-transport", "simd", "ureq-client"]
default-features = false

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
debug = false

[profile.profiling]
inherits = "release"
debug = 2
strip = false
